/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppPdfParserRouteImport } from './routes/app/pdf-parser'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as ApiResumeImportRouteImport } from './routes/api/resume-import'
import { Route as ApiPolishRouteImport } from './routes/api/polish'
import { Route as ApiPdfParseRouteImport } from './routes/api/pdf-parse'
import { Route as ApiMineruParseRouteImport } from './routes/api/mineru-parse'
import { Route as ApiGrammarRouteImport } from './routes/api/grammar'
import { Route as ApiDocumentParseRouteImport } from './routes/api/document-parse'
import { Route as ApiAiConfigRouteImport } from './routes/api/ai-config'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppWorkbenchIdRouteImport } from './routes/app/workbench/$id'
import { Route as AppPreviewTemplateIdRouteImport } from './routes/app/preview-template/$id'
import { Route as AppDashboardTemplatesRouteImport } from './routes/app/dashboard/templates'
import { Route as AppDashboardSettingsRouteImport } from './routes/app/dashboard/settings'
import { Route as AppDashboardResumesRouteImport } from './routes/app/dashboard/resumes'
import { Route as AppDashboardDashboardRouteImport } from './routes/app/dashboard/dashboard'
import { Route as AppDashboardAiRouteImport } from './routes/app/dashboard/ai'
import { Route as ApiProxyImageRouteImport } from './routes/api/proxy/image'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPdfParserRoute = AppPdfParserRouteImport.update({
  id: '/app/pdf-parser',
  path: '/app/pdf-parser',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResumeImportRoute = ApiResumeImportRouteImport.update({
  id: '/api/resume-import',
  path: '/api/resume-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolishRoute = ApiPolishRouteImport.update({
  id: '/api/polish',
  path: '/api/polish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfParseRoute = ApiPdfParseRouteImport.update({
  id: '/api/pdf-parse',
  path: '/api/pdf-parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMineruParseRoute = ApiMineruParseRouteImport.update({
  id: '/api/mineru-parse',
  path: '/api/mineru-parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrammarRoute = ApiGrammarRouteImport.update({
  id: '/api/grammar',
  path: '/api/grammar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocumentParseRoute = ApiDocumentParseRouteImport.update({
  id: '/api/document-parse',
  path: '/api/document-parse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiConfigRoute = ApiAiConfigRouteImport.update({
  id: '/api/ai-config',
  path: '/api/ai-config',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppWorkbenchIdRoute = AppWorkbenchIdRouteImport.update({
  id: '/app/workbench/$id',
  path: '/app/workbench/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPreviewTemplateIdRoute = AppPreviewTemplateIdRouteImport.update({
  id: '/app/preview-template/$id',
  path: '/app/preview-template/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardTemplatesRoute = AppDashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardResumesRoute = AppDashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardDashboardRoute = AppDashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAiRoute = AppDashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppDashboardRoute,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy/image',
  path: '/api/proxy/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/ai-config': typeof ApiAiConfigRoute
  '/api/document-parse': typeof ApiDocumentParseRoute
  '/api/grammar': typeof ApiGrammarRoute
  '/api/mineru-parse': typeof ApiMineruParseRoute
  '/api/pdf-parse': typeof ApiPdfParseRoute
  '/api/polish': typeof ApiPolishRoute
  '/api/resume-import': typeof ApiResumeImportRoute
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/pdf-parser': typeof AppPdfParserRoute
  '/app/': typeof AppIndexRoute
  '/api/proxy/image': typeof ApiProxyImageRoute
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/preview-template/$id': typeof AppPreviewTemplateIdRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/ai-config': typeof ApiAiConfigRoute
  '/api/document-parse': typeof ApiDocumentParseRoute
  '/api/grammar': typeof ApiGrammarRoute
  '/api/mineru-parse': typeof ApiMineruParseRoute
  '/api/pdf-parse': typeof ApiPdfParseRoute
  '/api/polish': typeof ApiPolishRoute
  '/api/resume-import': typeof ApiResumeImportRoute
  '/app/pdf-parser': typeof AppPdfParserRoute
  '/app': typeof AppIndexRoute
  '/api/proxy/image': typeof ApiProxyImageRoute
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/preview-template/$id': typeof AppPreviewTemplateIdRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/api/ai-config': typeof ApiAiConfigRoute
  '/api/document-parse': typeof ApiDocumentParseRoute
  '/api/grammar': typeof ApiGrammarRoute
  '/api/mineru-parse': typeof ApiMineruParseRoute
  '/api/pdf-parse': typeof ApiPdfParseRoute
  '/api/polish': typeof ApiPolishRoute
  '/api/resume-import': typeof ApiResumeImportRoute
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/pdf-parser': typeof AppPdfParserRoute
  '/app/': typeof AppIndexRoute
  '/api/proxy/image': typeof ApiProxyImageRoute
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/dashboard': typeof AppDashboardDashboardRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/preview-template/$id': typeof AppPreviewTemplateIdRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/api/ai-config'
    | '/api/document-parse'
    | '/api/grammar'
    | '/api/mineru-parse'
    | '/api/pdf-parse'
    | '/api/polish'
    | '/api/resume-import'
    | '/app/dashboard'
    | '/app/pdf-parser'
    | '/app/'
    | '/api/proxy/image'
    | '/app/dashboard/ai'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/preview-template/$id'
    | '/app/workbench/$id'
    | '/app/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/api/ai-config'
    | '/api/document-parse'
    | '/api/grammar'
    | '/api/mineru-parse'
    | '/api/pdf-parse'
    | '/api/polish'
    | '/api/resume-import'
    | '/app/pdf-parser'
    | '/app'
    | '/api/proxy/image'
    | '/app/dashboard/ai'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/preview-template/$id'
    | '/app/workbench/$id'
    | '/app/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/api/ai-config'
    | '/api/document-parse'
    | '/api/grammar'
    | '/api/mineru-parse'
    | '/api/pdf-parse'
    | '/api/polish'
    | '/api/resume-import'
    | '/app/dashboard'
    | '/app/pdf-parser'
    | '/app/'
    | '/api/proxy/image'
    | '/app/dashboard/ai'
    | '/app/dashboard/dashboard'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/preview-template/$id'
    | '/app/workbench/$id'
    | '/app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRoute
  ApiAiConfigRoute: typeof ApiAiConfigRoute
  ApiDocumentParseRoute: typeof ApiDocumentParseRoute
  ApiGrammarRoute: typeof ApiGrammarRoute
  ApiMineruParseRoute: typeof ApiMineruParseRoute
  ApiPdfParseRoute: typeof ApiPdfParseRoute
  ApiPolishRoute: typeof ApiPolishRoute
  ApiResumeImportRoute: typeof ApiResumeImportRoute
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppPdfParserRoute: typeof AppPdfParserRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  AppPreviewTemplateIdRoute: typeof AppPreviewTemplateIdRoute
  AppWorkbenchIdRoute: typeof AppWorkbenchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pdf-parser': {
      id: '/app/pdf-parser'
      path: '/app/pdf-parser'
      fullPath: '/app/pdf-parser'
      preLoaderRoute: typeof AppPdfParserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resume-import': {
      id: '/api/resume-import'
      path: '/api/resume-import'
      fullPath: '/api/resume-import'
      preLoaderRoute: typeof ApiResumeImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polish': {
      id: '/api/polish'
      path: '/api/polish'
      fullPath: '/api/polish'
      preLoaderRoute: typeof ApiPolishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf-parse': {
      id: '/api/pdf-parse'
      path: '/api/pdf-parse'
      fullPath: '/api/pdf-parse'
      preLoaderRoute: typeof ApiPdfParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mineru-parse': {
      id: '/api/mineru-parse'
      path: '/api/mineru-parse'
      fullPath: '/api/mineru-parse'
      preLoaderRoute: typeof ApiMineruParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grammar': {
      id: '/api/grammar'
      path: '/api/grammar'
      fullPath: '/api/grammar'
      preLoaderRoute: typeof ApiGrammarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/document-parse': {
      id: '/api/document-parse'
      path: '/api/document-parse'
      fullPath: '/api/document-parse'
      preLoaderRoute: typeof ApiDocumentParseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-config': {
      id: '/api/ai-config'
      path: '/api/ai-config'
      fullPath: '/api/ai-config'
      preLoaderRoute: typeof ApiAiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/workbench/$id': {
      id: '/app/workbench/$id'
      path: '/app/workbench/$id'
      fullPath: '/app/workbench/$id'
      preLoaderRoute: typeof AppWorkbenchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/preview-template/$id': {
      id: '/app/preview-template/$id'
      path: '/app/preview-template/$id'
      fullPath: '/app/preview-template/$id'
      preLoaderRoute: typeof AppPreviewTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/templates': {
      id: '/app/dashboard/templates'
      path: '/templates'
      fullPath: '/app/dashboard/templates'
      preLoaderRoute: typeof AppDashboardTemplatesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/settings': {
      id: '/app/dashboard/settings'
      path: '/settings'
      fullPath: '/app/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/resumes': {
      id: '/app/dashboard/resumes'
      path: '/resumes'
      fullPath: '/app/dashboard/resumes'
      preLoaderRoute: typeof AppDashboardResumesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/dashboard': {
      id: '/app/dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard/dashboard'
      preLoaderRoute: typeof AppDashboardDashboardRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/ai': {
      id: '/app/dashboard/ai'
      path: '/ai'
      fullPath: '/app/dashboard/ai'
      preLoaderRoute: typeof AppDashboardAiRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/api/proxy/image': {
      id: '/api/proxy/image'
      path: '/api/proxy/image'
      fullPath: '/api/proxy/image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardAiRoute: typeof AppDashboardAiRoute
  AppDashboardDashboardRoute: typeof AppDashboardDashboardRoute
  AppDashboardResumesRoute: typeof AppDashboardResumesRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardTemplatesRoute: typeof AppDashboardTemplatesRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAiRoute: AppDashboardAiRoute,
  AppDashboardDashboardRoute: AppDashboardDashboardRoute,
  AppDashboardResumesRoute: AppDashboardResumesRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardTemplatesRoute: AppDashboardTemplatesRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRoute,
  ApiAiConfigRoute: ApiAiConfigRoute,
  ApiDocumentParseRoute: ApiDocumentParseRoute,
  ApiGrammarRoute: ApiGrammarRoute,
  ApiMineruParseRoute: ApiMineruParseRoute,
  ApiPdfParseRoute: ApiPdfParseRoute,
  ApiPolishRoute: ApiPolishRoute,
  ApiResumeImportRoute: ApiResumeImportRoute,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppPdfParserRoute: AppPdfParserRoute,
  AppIndexRoute: AppIndexRoute,
  ApiProxyImageRoute: ApiProxyImageRoute,
  AppPreviewTemplateIdRoute: AppPreviewTemplateIdRoute,
  AppWorkbenchIdRoute: AppWorkbenchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
